package dongyuan.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import dongyuan.database.entity.Company;
import dongyuan.database.entity.User;
import dongyuan.database.entity.Shop;

import dongyuan.database.greendao.CompanyDao;
import dongyuan.database.greendao.UserDao;
import dongyuan.database.greendao.ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig shopDaoConfig;

    private final CompanyDao companyDao;
    private final UserDao userDao;
    private final ShopDao shopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyDaoConfig = daoConfigMap.get(CompanyDao.class).clone();
        companyDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        companyDao = new CompanyDao(companyDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);

        registerDao(Company.class, companyDao);
        registerDao(User.class, userDao);
        registerDao(Shop.class, shopDao);
    }
    
    public void clear() {
        companyDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        shopDaoConfig.clearIdentityScope();
    }

    public CompanyDao getCompanyDao() {
        return companyDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

}
